/*AUTOR: JUAN SILVESTRE RAMIREZ BECERRA
COLABORACION:JOSE MARTIN RUIZ COSS
			 ANGEL CHRISTIAN ALVAREZ TRUJILLO
MATERIA:PAGINAS WEB
*/

/***************CREACION BASE DE DATOS**********************/
CREATE DATABASE TACOSWORL;
USE TACOSWORL;

/***************  CREACION DE TABLAS  **********************/
CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO VARCHAR(30) NOT NULL,
CONTRASEÑA VARCHAR(20)NOT NULL,
TELEFONO VARCHAR(20)NULL,
CALLE VARCHAR(50)NULL,
CODIGO_POSTAL INT NULL,
LOCALIDAD VARCHAR(40)NULL,
ROL VARCHAR(30) NOT NULL
);

CREATE TABLE TAQUERIA(
ID_TAQUERIA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ESTATUSBT BIT NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CALLE VARCHAR(50) NOT NULL,
CODIGO_POSTAL INT NOT NULL,
LOCALIDAD VARCHAR(40) NOT NULL,
ALTITUD GEOMETRY NOT NULL,
LATITUD GEOMETRY NOT NULL,
ID_USUARIO INT NOT NULL,
ESTATUS_SUCURSAL BIT NOT NULL);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
TIPO VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(60) NOT NULL,
PRECIO FLOAT NOT NULL,
ESTATUS BIT NOT NULL
);

CREATE TABLE PEDIDOS(
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_TAQUERIA INT NOT NULL,
ID_USUARIO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT NOT NULL,
OBSERVACION VARCHAR(50),
ESTATUS BIT NOT NULL
);

CREATE TABLE PROMOCION(
ID_PROMOCION INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_TAQUERIA INT NOT NULL,
FECHAINI DATE NOT NULL,
FECHAFIN DATE NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
IMAGEN BLOB
);

CREATE TABLE BOLSA_TRABAJO(
ID_BOLSA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
SUELDO FLOAT NULL
);

CREATE TABLE COMENTARIOS(
ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_TAQUERIA INT NOT NULL,
ID_USUARIO INT NOT NULL,
COMENTARIO VARCHAR(100) NULL,
FECHA DATE NOT NULL 
);

/***************CREACION DE LLAVES FORANEAS**********************/
ALTER TABLE TAQUERIA ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_TAQUERIA) REFERENCES TAQUERIA(ID_TAQUERIA);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
ALTER TABLE PROMOCION ADD FOREIGN KEY(ID_TAQUERIA) REFERENCES TAQUERIA(ID_TAQUERIA);
ALTER TABLE COMENTARIO ADD FOREIGN KEY(ID_TAQUERIA) REFERENCES TAQUERIA(ID_TAQUERIA);
ALTER TABLE COMENTARIO ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

/***************    INSERCION DE DATOS    **********************/
/*TIPO DE ROLES: 1.-ADMINISTRADOR
				 2.-GERENTE
                 3.-USUARIO*/
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,CONTRASEÑA,TELEFONO,CALLE,CODIGO_POSTAL,LOCALIDAD,ROL) VALUES('JUAN SILVESTRE','RAMÍREZ BECERRA','trebol_silvestre14@hotmail.com','tacosZas123',4774408656,'BRICHO# 213',37108,'VALLE HERMOSO, LEON, GUANAJUATO','USUARIO');
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,CONTRASEÑA,TELEFONO,CALLE,CODIGO_POSTAL,LOCALIDAD,ROL) VALUES('JOSÉ MARTÍN','RUIZ COSS','MARTIN69ENCUATRO@gmail.com','ZaZatacos666',4733564189,'Anegeles# 235',35103,'LEON MODERNO, LEON, GUANAJUATO','GERENTE');
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,CONTRASEÑA,TELEFONO,CALLE,CODIGO_POSTAL,LOCALIDAD,ROL) VALUES('ANGEL CHRISTIAN','ALVAREZ TRUJILLO','trujillo69@hotmail.com','VamosTacos123',4772634859,'DONATELO# 313',39101,'LEON 1, LEON, GUANAJUATO','USUARIO');

INSERT INTO TAQUERIA(ID_TAQUERIA,ESTATUSBT,TELEFONO,NOMBRE,CALLE,CODIGO_POSTAL,LOCALIDAD,ALTITUD,LATITUD,ID_USUARIO,ESTATUS_SUCURSAL) VALUES();


/*************** CONSULTAR TABLAS DE LA BASE DE DATOS ***********/

SELECT * FROM BOLSA_TRABAJO;
SELECT * FROM PEDIDOS;
SELECT * FROM PRODUCTO;
SELECT * FROM PROMOCION;
SELECT * FROM TAQUERIA;
SELECT * FROM USUARIO;
/**************  PRUEBAS DE LA BASE DE DATOS TRANSACT   *********/
DROP DATABASE TACOSWORL;
